/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/apple.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/apple.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_apple.geometry} material={materials.red} />
      <mesh geometry={nodes.Mesh_apple_1.geometry} material={materials.brown} />
      <mesh geometry={nodes.Mesh_apple_2.geometry} material={materials.green} />
    </group>
  )
}

useGLTF.preload('/apple.gltf')
